server:
  port: 8888


spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git: # ????? ???? ??? Gitdmf ghkfdyd
          uri: 'https://github.com/sengjun0624/config-repository.git'
