spring:
  application:
    name: vet-service

  datasource:
    url: jdbc:mysql://localhost:3306/petclinic_vet
    username: ${USER}
    password: ${PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  show-sql: true
  format-sql: true
